name: 'client360x_dbt'
version: '1.0.0'
config-version: 2

# This points to the profile in your profiles.yml file
profile: 'client360x_profile'

# Directory paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Defining materialization hierarchy (Elite Best Practice)
# Defining materialization hierarchy
models:
  client360x_dbt:
    # Staging models represent 1:1 raw mappings. We materialize as tables.
    staging:
      +materialized: table
      +schema: staging
    
    # Intermediate models contain complex joins/aggregations. We make them tables.
    intermediate:
      +materialized: table
      +schema: intermediate
    # Marts contain clean, verified datasets. We make them tables.
    marts:
      +materialized: table
      +schema: marts

seeds:
  client360x_dbt:
    # Specify columns configurations for region seeds mapping
    ref_region_mapping:
      +column_types:
        region_code: varchar(3)
        region_name: varchar(100)