version: 2

sources:
  - name: dev
    database: CLIENT360X_DB
    schema: DEVELOPMENT
    description: "Raw source database representing the transactional systems of Client360X."
    tables:
      - name: branch
      - name: card
      - name: loan
      - name: account
      - name: transaction
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: txn_date
      - name: card_raw
      - name: customer_raw