version: 2

models:
  - name: dim_customer
    columns:
      - name: cust_id
        tests: [unique, not_null]
  - name: dim_branch
    columns:
      - name: branch_id
        tests: [unique, not_null]
  - name: dim_card
    columns:
      - name: card_id
        tests: [unique, not_null]
  - name: fct_loans
    columns:
      - name: loan_id
        tests: [unique, not_null]
      - name: cust_id
        tests:
          - relationships: {to: ref('dim_customer'), field: cust_id}
  - name: fct_transactions
    columns:
      - name: txn_id
        tests: [unique, not_null]
      - name: cust_id
        tests:
          - relationships: {to: ref('dim_customer'), field: cust_id}
      - name: branch_id
        tests:
          - relationships: {to: ref('dim_branch'), field: branch_id}